# Generated by Django 5.2.6 on 2025-09-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=100)),
                ('person_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('person_lastname', models.CharField(max_length=100)),
                ('person_age', models.IntegerField(default=0)),
                ('person_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('person_email', models.EmailField(max_length=254, unique=True)),
                ('person_contact', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
